{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mcp-trino.fullname" . }}
  labels:
    {{- include "mcp-trino.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mcp-trino.fullname" . }}
  labels:
    {{- include "mcp-trino.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mcp-trino.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mcp-trino.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}