{{- if or .Values.trino.password .Values.trino.oauth.jwtSecret .Values.trino.oauth.oidc.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-trino.fullname" . }}
  labels:
    {{- include "mcp-trino.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.trino.password }}
  TRINO_PASSWORD: {{ .Values.trino.password | b64enc }}
  {{- end }}
  {{- if .Values.trino.oauth.jwtSecret }}
  JWT_SECRET: {{ .Values.trino.oauth.jwtSecret | b64enc }}
  {{- end }}
  {{- if .Values.trino.oauth.oidc.clientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.trino.oauth.oidc.clientSecret | b64enc }}
  {{- else if and .Values.trino.oauth.enabled (ne .Values.trino.oauth.provider "hmac") }}
  OIDC_CLIENT_SECRET: {{ required "A clientSecret is required for OIDC providers" .Values.trino.oauth.oidc.clientSecret | b64enc }}
  {{- end }}
{{- end }}