apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-trino.fullname" . }}
  labels:
    {{- include "mcp-trino.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.eks.loadBalancer.annotations }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.eks.loadBalancer.enabled }}
    {{- with .Values.eks.loadBalancer.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mcp-trino.selectorLabels" . | nindent 4 }}