run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - revive
    - misspell
    - gofmt
    - goimports
    - gocritic
    - gocyclo
    - bodyclose
    - noctx
    - unconvert

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    rules:
      - name: exported
  gosec:
    excludes:
      - G204
      - G112
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - opinionated
    disabled-checks:
      - exitAfterDefer

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
