version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true # Disable all default linters first
  enable:
    - errcheck
    # - gosimple # Not available in this version, functionality likely in staticcheck
    - govet
    - ineffassign
    - staticcheck
    # - stylecheck # Not available in this version, functionality likely in staticcheck/revive
    - unconvert
    - unused
    - revive
    - nolintlint
  # no lll (line length linter) as per Google Style Guide
  # gofmt and goimports are formatters, not linters.
  # golangci-lint handles them separately.

# I might need to add configuration for specific linters later if the output is too noisy
# or if specific Google Style Guide points need more targeted rules.
# Particularly, 'revive' might need configuration for stricter Google Style alignment.

# For now, default settings for the enabled linters will be used.

issues:
  # Exclude known issues or specific paths if necessary after first run
  # exclude-rules:
  #   - path: _test\.go
  #     linters:
  #       - dupl