# Add version specification at the top
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/server/main.go
    binary: mcp-trino
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - Merge pull request
      - Merge branch

# Explicitly configure GitHub Releases
release:
  github:
    owner: "{{.Env.GITHUB_REPOSITORY_OWNER}}"
    name: "mcp-trino"
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

dockers:
  - image_templates:
      - "ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/mcp-trino:{{ .Version }}"
      - "ghcr.io/{{.Env.GITHUB_REPOSITORY_OWNER}}/mcp-trino:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    # Add GitHub Container Registry push configuration
    use: docker
    push_flags:
      - "--tls-verify=false"
